### ISSUE TITLE
Fails to launch

### ISSUE THREAD

**Issue by tonymullen** [anton-k/processing-for-haskell#3]
Running

`stack build`

in the project directory and then 

`stack exec -- runhaskell examples/Math/AdditiveWave.hs`

Results in the following error. 

`2022-04-19 16:38:25.661 ghc[69318:11738676] GLUT Fatal Error: internal error: NSInternalInconsistencyException, reason: nextEventMatchingMask should only be called from the Main Thread!`

Running OS X 10.15.7, 

I'd love to get this project running. Let me know if I'm missing something.

**Comment by anton-k** [comment]
Hi Tony!

Sorry for delay in reply.. 
I've tried the line and it works fine for me on tip of the current master.
I'm on Linux. Maybe it's something with glut peculiarities on Mac.

Runhaskell executes without threaded option, maybe it complains about that.
Can you try to compile the example with threaded support and then run the executable:

```
stack exec -- ghc -O2 -threaded examples/Math/AdditiveWave.hs
./examples/Math/AdditiveWave
```

**Comment by anton-k** [comment]
![image](https://user-images.githubusercontent.com/1488818/164972272-b100e1dd-3af2-41c7-885b-70592176a794.png)

**Comment by anton-k** [comment]
I can not access any Mac based machine to troubleshoot :(

**Comment by tonymullen** [comment]
Thanks! Yes, compiling first solves the problem.
